service: otel-poc-new

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: index.handler
    layers:
      - arn:aws:lambda:us-east-1:184161586896:layer:opentelemetry-nodejs-0_9_0:4
    events:
      - http:
          path: /{proxy+}
          method: any
    environment:
      AWS_LAMBDA_EXEC_WRAPPER: "/opt/otel-handler"
      OTEL_SERVICE_NAME: "lambda-nodejs-otel-agent-prd"
      OTEL_TRACES_SAMPLER: "always_on"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_METRICS_EXPORTER: "otlp"
      OTEL_LOGS_EXPORTER: "otlp"
      OTEL_LOG_LEVEL: "ERROR"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://54.160.207.36:4318/"
      OTEL_PROPAGATORS: "tracecontext,baggage, xray"
      OTEL_LAMBDA_TRACE_MODE: "capture"
      OTEL_RESOURCE_ATTRIBUTES: "service.name=lambda-nodejs-otel-agent,environment=production"
